services:
  redis:
    image: redis:latest
    ports:
      - "${DB_PORT}:6379"
    
  scraper:
    image: go_scraper:latest
    environment:
      INTERVAL: ${INTERVAL}
      ENDPOINTS: ${ENDPOINTS}
      WINDOW_SIZE: ${WINDOW_SIZE}
      DB_PORT: ${DB_PORT}
      HOST: ${HOST}
  
  dashboard:
    image: dashboard:latest
    environment:
      INTERVAL: ${INTERVAL}
      ENDPOINTS: ${ENDPOINTS}
      WINDOW_SIZE: ${WINDOW_SIZE}
      DB_PORT: ${DB_PORT}
      HOST: ${HOST}
    ports:
      - "${DASHBOARD_PORT}:8501"